---
version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.7.2'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: 'docs'
      SPHINX_SOURCE_DIR: ''
      SPHINX_OUTPUT_DIR: '_build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'nimble install -d'
      - 'uv sync --frozen'
      - 'lefthook install'
  setup-ci:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --group=lint'
  release-*:
    desc: 'Run edit to update version'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync --all-groups' # To write out as lock-file
