## Document model of Gitignore file generated by gigi.
##
## See ``docs/spec/format.rst`` for format.
import std/strutils
import ./source

const
  MARKER_VERSION = "#:gigi:version: "
  MARKER_ARGUMENTS = "#:gigi:arguments: "
  MARKER_SOURCE = "#:gigi:source: "
  MARKER_USER = "#:gigi:user"

type
  SourceSection* = object
    source*: Source
    content*: string

  GitignoreDoc* = object
    version*: string
    arguments*: seq[string]
    sections*: seq[SourceSection]
    userContent*: string

proc render*(doc: GitignoreDoc): string =
  var lines: seq[string] = @[]
  lines.add MARKER_VERSION & doc.version
  lines.add MARKER_ARGUMENTS & doc.arguments.join(" ")
  lines.add ""
  for section in doc.sections:
    lines.add MARKER_SOURCE & $section.source
    lines.add section.content
    lines.add ""
  lines.add MARKER_USER
  if doc.userContent != "":
    lines.add doc.userContent
  result = lines.join("\n")
