---
name: 'Run standard CI'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c  # v4.0.4
        with:
          aqua_version: v2.55.0
          policy_allow: 'true'
      - name: 'Configure workspace for ci'
        run: 'task setup-ci'
      - name: 'Run linters'
        run: 'lefthook run pre-commit --all-files'
  test:
    needs: ['lint']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - '2.2.12'
    steps:
      - uses: actions/checkout@v4
      - name: Cache Nim resources
        id: cache_nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: nimcaches--${{ matrix.os }}-${{ matrix.nim-version }}
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: |
          nimble build -Y
          nimble test -Y
  docs-test:
    needs: ['lint']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0  # v4.0.0
        with:
          aqua_version: v2.55.0
          policy_allow: 'true'
      - name: Configure venv
        run: |
          uv sync --frozen --docs
      - name: Build document
        run: |
          task --yes docs:build-linkcheck docs:build-dirhtml
