---
name: 'Run standard CI'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6'
      - uses: 'attakei/devkit/actions/setup-aqua@main'
      - name: 'Configure workspace for ci'
        run: 'task --yes setup-ci'
      - name: 'Run linters'
        run: 'lefthook run pre-commit --all-files'
  test:
    needs: ['lint']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - '2.2.12'
    steps:
      - uses: 'actions/checkout@v6'
      - uses: './.github/actions/setup-nim'
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: |
          nimble build -Y
          nimble test -Y
  docs-test:
    needs: ['lint']
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v6'
      - uses: 'attakei/devkit/actions/setup-aqua@main'
      - name: Configure venv
        run: |
          uv sync --frozen --group=docs
      - name: Build document
        run: |
          task --yes docs:build-linkcheck docs:build-dirhtml
